# This file is covered by the LICENSE file in the root of this project.
# Developed by: Xieyuanli Chen
# Configuration (specifying all the paths)
# --------------------------------------------------------------------

# Inputs
# the root of raw LiDAR scans
scan_root: '/home/robot/Repository/data_odometry_velodyne/dataset'
# the root of mos predictions
mos_pred_root: 'log'
# the root of semantic predictions
semantic_pred_root: 'data/predictions_salsanext_sem_valid'

# Outputs
split: valid  # choose from (train, valid, test)
combined_results_root: 'log'
clean_scan_root: 'data'


